log:
  # 日志级别1-5
  level: 4
  # 日志颜色开关
  colorSwitch: true
host: 0.0.0.0
socks:
  debugSwitch: false
  port: 1080
  # 客户端连接超时设置，单位秒
  client:
    timeout: 15
  # 下游代理连接超时设置，单位秒
  target:
    timeout: 15
  # 下游代理地址，目前不支持多级代理
  proxy:
    - http://127.0.0.1:8080
  # ture：dns解析交给socks2https工具完成，false：dns解析交给下游代理完成
  # 建议默认使用false
  bound: false